### ISSUE TITLE
Why reinvent the wheel ?

### ISSUE THREAD

**Issue by ststeiger** [signal-csharp/curve25519-dotnet#1]
Why reinvent the wheel ?

http://javadox.com/org.bouncycastle/bcprov-jdk15on/1.53/org/bouncycastle/math/ec/custom/djb/Curve25519.html¨

https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/ec/CustomNamedCurves.cs

**Comment by golf1052** [comment]
I'm not sure what you mean. I have no problem with using the Bouncy Castle library but we do have a restriction on this library that it needs to support being run on Windows 10 build 15063 (Creators Update) because of https://github.com/signal-csharp/Signal-Windows/issues/205 which restricts its `TargetFramework` to netstandard1.4 or lower.

In terms of matching what [Signal-Android](https://github.com/signalapp/signal-android) does it's much easier when implementing to just port over Signal-Android's libraries. I'm happy to look at and accept a PR that replaces this implementation with another one as long as it works with [libsignal-protocol-dotnet](https://github.com/signal-csharp/libsignal-protocol-dotnet).
